@extends('layouts.app')
@section('title', 'Обзор')
@section('content')
<div class="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p class="text-sm text-amber-500">{{ $project->production_stage }}</p><h1>{{ $project->localized('title_ru') }}</h1><p class="mt-2 max-w-3xl text-slate-600">{{ $project->localized('logline') }}</p></div><a class="btn-secondary" href="{{ route('assets.create') }}">Добавить материал</a></div>
<section class="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="card"><p class="muted">Общая готовность</p><p class="mt-2 text-4xl font-semibold">{{ $completion }}%</p><div class="mt-4 h-2 overflow-hidden rounded-full bg-mist-100"><div class="h-full bg-amber-500" style="width:{{ $completion }}%"></div></div></div><div class="card"><p class="muted">Выполнено</p><p class="mt-2 text-4xl font-semibold text-emerald-700">{{ $stats['done'] }}</p><p class="mt-2 muted">Открыто: {{ $stats['open'] }}</p></div><div class="card"><p class="muted">Предупреждения</p><p class="mt-2 text-4xl font-semibold text-amber-600">{{ $stats['warning'] }}</p><p class="mt-2 muted">Ручные решения с нехваткой</p></div><div class="card"><p class="muted">Ожидают проверки</p><p class="mt-2 text-4xl font-semibold">{{ $pendingAssets }}</p><p class="mt-2 muted">Сцен: {{ $reviewScenes }}</p></div></section>
<div class="mt-7 grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><section class="card"><div class="flex items-center justify-between"><h2>Готовность разделов</h2><a href="{{ route('checklist.index') }}" class="text-sm text-amber-600">Открыть чек-лист</a></div><div class="mt-5 space-y-4">@foreach($sections as $section) @php
    $sectionItems = $section->items->concat($section->children->flatMap->items);
    $sectionProgress = $sectionItems->count() ? round($sectionItems->avg('progress')) : 0;
@endphp<div><div class="mb-1.5 flex justify-between text-sm"><span>{{ $section->title }}</span><span>{{ $sectionProgress }}%</span></div><div class="h-2 rounded-full bg-mist-100"><div class="h-2 rounded-full bg-ink-800" style="width:{{ $sectionProgress }}%"></div></div></div>@endforeach</div></section><section class="card"><h2>Нужны материалы</h2><div class="mt-4 space-y-3">@forelse($missingItems as $item)<a href="{{ route('checklist.index') }}#item-{{ $item->id }}" class="block rounded-xl bg-mist-50 p-3"><p class="font-medium">{{ $item->title }}</p><p class="mt-1 text-xs text-slate-500">{{ $item->warning_text ?: 'Требования ещё не закрыты' }}</p></a>@empty<p class="muted">Все обязательные требования закрыты.</p>@endforelse</div></section></div>
<div class="mt-7 grid gap-6 xl:grid-cols-2"><section class="card"><div class="flex justify-between"><h2>Последние материалы</h2><a class="text-sm text-amber-600" href="{{ route('assets.index') }}">Все материалы</a></div><div class="mt-4 grid gap-3 sm:grid-cols-2">@forelse($recentAssets as $asset)<a class="rounded-xl border border-mist-100 p-3 hover:border-amber-400" href="{{ route('assets.show', $asset) }}"><p class="font-medium">{{ $asset->title }}</p><p class="mt-1 text-xs text-slate-500">{{ $asset->type }} · {{ $asset->status }}</p></a>@empty<p class="muted">Материалов пока нет.</p>@endforelse</div></section><section class="card"><h2>Последние изменения</h2><div class="mt-4 divide-y divide-mist-100">@forelse($activity as $log)<div class="py-3 first:pt-0"><p class="text-sm font-medium">{{ $log->action }}</p><p class="mt-1 text-xs text-slate-500">{{ $log->description }} · {{ $log->created_at->diffForHumans() }}</p></div>@empty<p class="muted">История появится после первого изменения.</p>@endforelse</div></section></div>
<section class="card mt-7"><div class="flex items-center justify-between"><h2>OpenAI за текущий месяц</h2><a href="{{ route('ai.index') }}" class="text-sm text-amber-600">Открыть ИИ-помощник</a></div><div class="mt-4 grid gap-4 sm:grid-cols-3 xl:grid-cols-6"><div><p class="muted">Сегодня</p><p class="mt-1 text-xl font-semibold">${{ number_format($aiUsage['today'],4) }}</p></div><div><p class="muted">Месяц</p><p class="mt-1 text-xl font-semibold">${{ number_format($aiUsage['month'],4) }}</p></div><div><p class="muted">Лимит</p><p class="mt-1 text-xl font-semibold">{{ $aiUsage['budget'] > 0 ? '$'.number_format($aiUsage['budget'],2) : 'Не задан' }}</p></div><div><p class="muted">Текст</p><p class="mt-1 text-xl font-semibold">{{ $aiUsage['text'] }}</p></div><div><p class="muted">Изображения</p><p class="mt-1 text-xl font-semibold">{{ $aiUsage['images'] }}</p></div><div><p class="muted">Ошибки</p><p class="mt-1 text-xl font-semibold">{{ $aiUsage['errors'] }}</p></div></div><div class="mt-6 grid gap-6 md:grid-cols-2"><div><h3>Расход по пользователям</h3><div class="mt-2 space-y-2">@forelse($aiByUsers as $row)<div class="flex justify-between text-sm"><span>{{ $row->name }}</span><span>${{ number_format($row->total_cost,4) }}</span></div>@empty<p class="muted">Данных пока нет.</p>@endforelse</div></div><div><h3>Расход по сценам</h3><div class="mt-2 space-y-2">@forelse($aiByScenes as $row)<div class="flex justify-between gap-4 text-sm"><span>{{ $row->code }} — {{ $row->title }}</span><span>${{ number_format($row->total_cost,4) }}</span></div>@empty<p class="muted">Запросы ещё не привязаны к сценам.</p>@endforelse</div></div></div></section>
@endsection
