@extends('layouts.app')
@section('title', 'Редактирование проекта')
@section('content')
<div><p class="text-sm text-amber-500">Новая версия карточки</p><h1>Редактирование проекта</h1></div><form method="POST" action="{{ route('project.update') }}" class="card mt-7 space-y-6">@csrf @method('PUT')
<div class="grid gap-4 md:grid-cols-3"><div><label>Название (RU)</label><input name="title_ru" value="{{ old('title_ru',$project->title_ru) }}" required></div><div><label>Title (EN)</label><input name="title_en" value="{{ old('title_en',$project->title_en) }}"></div><div><label>Titel (DE)</label><input name="title_de" value="{{ old('title_de',$project->title_de) }}"></div></div>
@foreach(['' => 'RU', '_en' => 'EN', '_de' => 'DE'] as $suffix => $language)<div class="field-grid"><div><label>Слоган ({{ $language }})</label><textarea name="tagline{{ $suffix }}">{{ old('tagline'.$suffix,$project->{'tagline'.$suffix}) }}</textarea></div><div><label>Логлайн ({{ $language }})</label><textarea name="logline{{ $suffix }}">{{ old('logline'.$suffix,$project->{'logline'.$suffix}) }}</textarea></div></div>@endforeach
<div><label>Краткий синопсис</label><textarea class="min-h-52" name="synopsis">{{ old('synopsis',$project->synopsis) }}</textarea></div>
<div class="grid gap-4 md:grid-cols-3"><div><label>Жанр</label><input name="genre" value="{{ old('genre',$project->genre) }}"></div><div><label>Продолжительность</label><input name="duration" value="{{ old('duration',$project->duration) }}"></div><div><label>Стадия</label><input name="production_stage" value="{{ old('production_stage',$project->production_stage) }}" required></div><div><label>Формат кадра</label><input name="aspect_ratio" value="{{ old('aspect_ratio',$project->aspect_ratio) }}"></div><div><label>Частота кадров</label><input type="number" name="frame_rate" value="{{ old('frame_rate',$project->frame_rate) }}"></div><div><label>Разрешение</label><input name="resolution" value="{{ old('resolution',$project->resolution) }}"></div><div><label>Язык</label><input name="language" value="{{ old('language',$project->language) }}" required></div></div>
<div><label>Доска фильма в Adobe Firefly</label><input type="url" name="firefly_board_url" value="{{ old('firefly_board_url',$project->firefly_board_url) }}" placeholder="https://firefly.adobe.com/boards/..."><p class="mt-2 text-xs text-slate-500">Ссылка открывается только авторизованным участникам, которым предоставлен доступ в Adobe.</p></div>
@foreach(['visual_principle'=>'Визуальный принцип','sound_principle'=>'Звуковой принцип','color_palette'=>'Цветовая палитра','camera_rules'=>'Правила камеры'] as $name=>$label)<div><label>{{ $label }}</label><textarea class="min-h-40" name="{{ $name }}">{{ old($name,$project->{$name}) }}</textarea></div>@endforeach<div class="flex gap-3"><button class="btn-primary">Сохранить новую версию</button><a href="{{ route('project.show') }}" class="btn-secondary">Отмена</a></div></form>
@endsection
