<?php

return [
    'Обзор' => 'Overview', 'О проекте' => 'About the project', 'Акты, сцены и кадры' => 'Acts, scenes and shots', 'Чек-лист' => 'Checklist', 'Материалы' => 'Materials', 'Персонажи' => 'Characters', 'Места' => 'Locations', 'Реквизит и одежда' => 'Props and wardrobe', 'Документы' => 'Documents', 'ИИ-помощник' => 'AI assistant', 'Публикации' => 'Publications', 'Команда' => 'Team', 'История изменений' => 'Change history',
    'Добавить материал' => 'Add material', 'Загрузить материал' => 'Upload material', 'Сохранить материал' => 'Save material', 'Новый материал' => 'New material', 'Название' => 'Title', 'Описание' => 'Description', 'Статус' => 'Status', 'Тип' => 'Type', 'Порядок' => 'Order', 'Сохранить' => 'Save', 'Отмена' => 'Cancel', 'Изменить' => 'Edit', 'Создать' => 'Create', 'Автор' => 'Author', 'Источник' => 'Source', 'Разрешение' => 'Permission', 'Комментарий' => 'Comment', 'Ответственный' => 'Assignee', 'Срок' => 'Due date', 'Поиск по названию' => 'Search by title', 'Все типы' => 'All types', 'Все статусы' => 'All statuses', 'Применить фильтры' => 'Apply filters', 'Скачать оригинал' => 'Download original', 'Открыть внешний файл' => 'Open external file', 'Предпросмотр недоступен' => 'Preview unavailable', 'Обновить статус' => 'Update status', 'Метаданные' => 'Metadata', 'Связано' => 'Linked to', 'Есть разрешение на использование' => 'Usage permission granted', 'Файл' => 'File', 'Внешняя ссылка' => 'External link', 'Текстовая заметка' => 'Text note', 'Категория' => 'Category', 'Без категории' => 'No category', 'Дата съёмки' => 'Shoot date', 'Загрузка' => 'Uploading',
    'Общая готовность' => 'Overall readiness', 'Выполнено' => 'Completed', 'Предупреждения' => 'Warnings', 'Ожидают проверки' => 'Awaiting review', 'Готовность разделов' => 'Section readiness', 'Открыть чек-лист' => 'Open checklist', 'Нужны материалы' => 'Materials needed', 'Последние материалы' => 'Recent materials', 'Все материалы' => 'All materials', 'Последние изменения' => 'Recent changes', 'Сегодня' => 'Today', 'Месяц' => 'Month', 'Лимит' => 'Limit', 'Не задан' => 'Not set', 'Текст' => 'Text', 'Изображения' => 'Images', 'Ошибки' => 'Errors', 'Данных пока нет.' => 'No data yet.', 'Материалов пока нет.' => 'No materials yet.',
    'Производственный чек-лист' => 'Production checklist', 'Автоматический учёт утверждённых материалов' => 'Automatic tracking of approved materials', 'Пересчитать всё' => 'Recalculate all', 'Требования' => 'Requirements', 'Не завершено' => 'Not completed', 'Добавить требование' => 'Add requirement', 'Отметить вручную' => 'Mark manually', 'Причина ручного решения' => 'Reason for manual decision', 'Сохранить решение' => 'Save decision', 'Новый пункт' => 'New item', 'Раздел / группа' => 'Section / group', 'Обязательный пункт' => 'Required item', 'Создать пункт' => 'Create item', 'Новый раздел' => 'New section', 'Родительский раздел' => 'Parent section', 'Верхний уровень' => 'Top level', 'Создать раздел' => 'Create section',
    'Производственная библиотека' => 'Production library', 'Новая запись' => 'New record', 'Роль' => 'Role', 'Возраст' => 'Age', 'Внешность' => 'Appearance', 'Телосложение' => 'Build', 'Одежда' => 'Wardrobe', 'Голос' => 'Voice', 'Движения' => 'Movement', 'Время суток' => 'Time of day', 'Погода' => 'Weather', 'Свет' => 'Lighting', 'Палитра' => 'Palette', 'Звуки' => 'Sounds', 'Цвет' => 'Colour', 'Размеры' => 'Dimensions', 'Состояние' => 'Condition', 'Требования непрерывности' => 'Continuity requirements',
    'Документы проекта' => 'Project documents', 'Редактировать сценарий' => 'Edit screenplay', 'Отменить редактирование' => 'Cancel editing', 'Работа с текстом через ИИ' => 'Work with text using AI', 'Название документа' => 'Document title', 'Тип документа' => 'Document type', 'Текст сценария' => 'Screenplay text', 'Комментарий к версии' => 'Version note', 'Сохранить новую версию' => 'Save new version', 'История версий' => 'Version history', 'Восстановить эту версию' => 'Restore this version',
    'Структура фильма' => 'Film structure', 'Новый акт' => 'New act', 'Новая сцена' => 'New scene', 'Новый кадр' => 'New shot', 'Номер' => 'Number', 'Код' => 'Code', 'Действие' => 'Action', 'Действие героя' => 'Hero action', 'Действие собаки' => 'Dog action', 'Крупность' => 'Shot size', 'Положение камеры' => 'Camera position', 'Движение камеры' => 'Camera movement', 'Звук' => 'Sound', 'Способ создания' => 'Creation method', 'Промпт' => 'Prompt', 'Создать акт' => 'Create act', 'Создать сцену' => 'Create scene', 'Создать кадр' => 'Create shot', 'Кадры ещё не добавлены.' => 'No shots added yet.', 'Сцен пока нет.' => 'No scenes yet.', 'Проанализировать сцену с ИИ' => 'Analyse scene with AI',
    'Карточка проекта' => 'Project card', 'Редактировать карточку' => 'Edit project card', 'Слоган' => 'Tagline', 'Логлайн' => 'Logline', 'Синопсис' => 'Synopsis', 'Визуальный принцип' => 'Visual principle', 'Звуковой принцип' => 'Sound principle', 'Камера и цвет' => 'Camera and colour', 'Параметры' => 'Specifications', 'Жанр' => 'Genre', 'Продолжительность' => 'Duration', 'Формат' => 'Format', 'Частота' => 'Frame rate', 'Язык' => 'Language', 'Стадия' => 'Stage', 'Редактирование проекта' => 'Edit project', 'Новая версия карточки' => 'New card version', 'Краткий синопсис' => 'Short synopsis', 'Сохранить новую версию' => 'Save new version',
    'Все участники имеют одинаковые права' => 'All members have equal permissions', 'Активен' => 'Active', 'Отключён' => 'Disabled', 'Новый пароль (необязательно)' => 'New password (optional)', 'Повторите пароль' => 'Repeat password', 'Добавить участника' => 'Add team member', 'Имя' => 'Name', 'Электронная почта' => 'Email address', 'Пароль' => 'Password', 'Добавить' => 'Add',
    'Ничего не публикуется автоматически' => 'Nothing is published automatically', 'Публичная страница' => 'Public website', 'Открыть сайт' => 'Open website', 'Главная страница' => 'Homepage', 'Пожертвования' => 'Donations', 'На сайте' => 'On website', 'Не показывается' => 'Hidden', 'Скрыть с сайта' => 'Hide from website', 'Показать на сайте' => 'Show on website', 'Новая публикация' => 'New publication', 'Создать и опубликовать' => 'Create and publish', 'Сохранить как черновик' => 'Save as draft', 'Добавить новый материал' => 'Add new media', 'Загрузить фото или видео' => 'Upload photo or video', 'Выбрать из медиатеки' => 'Choose from media library', 'Сохранить изменения' => 'Save changes', 'Публикаций пока нет.' => 'No publications yet.', 'Оформление главной' => 'Homepage design', 'Публичное описание (RU)' => 'Public description (RU)', 'Опубликованный контакт' => 'Public contact', 'Сохранить остальные настройки' => 'Save other settings', 'Посмотреть публичный сайт' => 'View public website', 'Поддержать создание фильма' => 'Support film production', 'Банковские реквизиты' => 'Bank details', 'Показывать блок на публичной странице' => 'Show block on public website', 'Сохранить настройки' => 'Save settings',
    'Работа с текстом' => 'Text tools', 'Действие' => 'Action', 'Собственное задание' => 'Custom task', 'Дополнительные требования' => 'Additional requirements', 'Исходный текст' => 'Source text', 'Получить предложение' => 'Get suggestion', 'Название результата' => 'Result title', 'Тип изображения' => 'Image type', 'Качество' => 'Quality', 'Низкое' => 'Low', 'Среднее' => 'Medium', 'Высокое' => 'High', 'Количество вариантов' => 'Number of variants', 'Создать новое' => 'Create new', 'Поставить в очередь' => 'Add to queue', 'История моих запросов' => 'My request history', 'Запросов ещё нет.' => 'No requests yet.', 'Применить' => 'Apply', 'Отклонить' => 'Reject', 'Скопировать' => 'Copy', 'Доработать' => 'Refine',
    'Защита от случайной перезаписи' => 'Protection from accidental overwrites', 'Показать изменённые поля' => 'Show changed fields', 'Было' => 'Before', 'Стало' => 'After', 'Изменений пока нет.' => 'No changes yet.', 'Восстановить состояние до правки' => 'Restore state before this change',
];
