@extends('layouts.app')
@section('title', 'Акты, сцены и кадры')
@section('content')
<div><p class="text-sm text-amber-500">Проект → акты → сцены → кадры</p><h1>Структура фильма</h1></div>
<div x-data="{ form: 'scene' }" class="mt-7 grid gap-6 xl:grid-cols-[1.35fr_.65fr]">
<section class="space-y-5">@foreach($project->acts as $act)<article class="card" x-data="{ open: true }"><button type="button" @click="open=!open" class="flex w-full items-start justify-between text-left"><div><p class="text-xs text-amber-600">Акт {{ $act->number }} · {{ $act->status }}</p><h2 class="mt-1">{{ $act->title }}</h2><p class="mt-2 text-sm text-slate-600">{{ $act->description }}</p></div><span class="text-slate-400" x-text="open ? '−' : '+'"></span></button>
<div x-show="open" class="mt-5 space-y-4">@forelse($act->scenes as $scene)<div class="rounded-2xl border border-mist-100 bg-mist-50 p-4"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-xs font-semibold text-amber-600">{{ $scene->code }} · {{ $scene->status }}</p><h3 class="mt-1">{{ $scene->title }}</h3><p class="mt-2 text-sm text-slate-600">{{ $scene->action_description }}</p><p class="mt-2 text-xs text-slate-500">{{ $scene->location?->name }} · {{ $scene->time_of_day }} · {{ $scene->weather }}</p></div><div class="flex gap-2"><a href="{{ route('ai.index',['scene'=>$scene->id]) }}" class="btn-secondary">Проанализировать сцену с ИИ</a>@if($scene->status==='Финал')<form method="POST" action="{{ route('structure.unlock',['scene',$scene]) }}">@csrf<button class="btn-secondary">Снять защиту</button></form>@endif</div></div>
<div class="mt-4 grid gap-3 md:grid-cols-2">@forelse($scene->shots as $shot)<div class="rounded-xl bg-white p-3"><p class="text-xs font-semibold text-amber-600">{{ $shot->code }} · {{ $shot->status }}</p><p class="mt-1 text-sm">{{ $shot->description }}</p><div class="mt-2 flex items-center justify-between gap-2"><p class="text-xs text-slate-500">{{ $shot->shot_size }} · {{ $shot->planned_duration_seconds }} сек.</p><a href="{{ route('ai.index',['shot'=>$shot->id]) }}" class="text-xs text-amber-700">Помощь ИИ</a></div></div>@empty<p class="muted">Кадры ещё не добавлены.</p>@endforelse</div></div>@empty<p class="muted">Сцен пока нет.</p>@endforelse</div></article>@endforeach</section>
<aside class="card self-start xl:sticky xl:top-7"><div class="grid grid-cols-3 gap-2 rounded-xl bg-mist-100 p-1 text-sm"><button type="button" @click="form='act'" :class="form==='act'&&'bg-white shadow-sm'" class="rounded-lg px-2 py-2">Акт</button><button type="button" @click="form='scene'" :class="form==='scene'&&'bg-white shadow-sm'" class="rounded-lg px-2 py-2">Сцена</button><button type="button" @click="form='shot'" :class="form==='shot'&&'bg-white shadow-sm'" class="rounded-lg px-2 py-2">Кадр</button></div>
<form x-show="form==='act'" method="POST" action="{{ route('acts.store') }}" class="mt-5 space-y-4">@csrf<h2>Новый акт</h2><div class="field-grid"><div><label>Номер</label><input type="number" name="number" min="1" required></div><div><label>Порядок</label><input type="number" name="sort_order" min="0" value="{{ $project->acts->count()+1 }}"></div></div><div><label>Название</label><input name="title" required></div><div><label>Описание</label><textarea name="description"></textarea></div><div><label>План, секунд</label><input type="number" name="planned_duration_seconds" min="0"></div><input type="hidden" name="status" value="Черновик"><button class="btn-primary w-full">Создать акт</button></form>
<form x-show="form==='scene'" method="POST" action="{{ route('scenes.store') }}" class="mt-5 space-y-4">@csrf<h2>Новая сцена</h2><div><label>Акт</label><select name="act_id" required>@foreach($project->acts as $act)<option value="{{ $act->id }}">Акт {{ $act->number }} — {{ $act->title }}</option>@endforeach</select></div><div class="field-grid"><div><label>Код</label><input name="code" placeholder="A1-S03" required></div><div><label>Номер</label><input name="number" type="number" min="1" required></div></div><div><label>Название</label><input name="title" required></div><div><label>Действие</label><textarea name="action_description"></textarea></div><div class="field-grid"><div><label>Место</label><select name="location_id"><option value="">—</option>@foreach($locations as $location)<option value="{{ $location->id }}">{{ $location->name }}</option>@endforeach</select></div><div><label>Ответственный</label><select name="assignee_id"><option value="">—</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></div><div><label>Время суток</label><input name="time_of_day"></div><div><label>Погода</label><input name="weather"></div></div><div><label>Персонажи</label><select name="character_ids[]" multiple class="min-h-28">@foreach($characters as $character)<option value="{{ $character->id }}">{{ $character->name }}</option>@endforeach</select></div><div><label>Реквизит</label><select name="prop_ids[]" multiple class="min-h-28">@foreach($props as $prop)<option value="{{ $prop->id }}">{{ $prop->name }}</option>@endforeach</select></div><div><label>Звуки</label><textarea name="sounds"></textarea></div><div><label>План, секунд</label><input type="number" name="planned_duration_seconds" min="0"></div><input type="hidden" name="status" value="Черновик"><button class="btn-primary w-full">Создать сцену</button></form>
<form x-show="form==='shot'" method="POST" action="{{ route('shots.store') }}" class="mt-5 space-y-4">@csrf<h2>Новый кадр</h2><div><label>Сцена</label><select name="scene_id" required>@foreach($project->acts->flatMap->scenes as $scene)<option value="{{ $scene->id }}">{{ $scene->code }} — {{ $scene->title }}</option>@endforeach</select></div><div class="field-grid"><div><label>Код</label><input name="code" placeholder="A1-S03-K07" required></div><div><label>Номер</label><input name="number" type="number" min="1" required></div></div><div><label>Описание кадра</label><textarea name="description" required></textarea></div><div class="field-grid"><div><label>Действие героя</label><input name="hero_action"></div><div><label>Действие собаки</label><input name="dog_action"></div><div><label>Крупность</label><input name="shot_size"></div><div><label>План, секунд</label><input type="number" name="planned_duration_seconds" min="0"></div></div><div><label>Положение камеры</label><textarea name="camera_position"></textarea></div><div><label>Движение камеры</label><textarea name="camera_movement"></textarea></div><div><label>Объектив / указание</label><input name="lens"></div><div><label>Звук</label><textarea name="sound"></textarea></div><div><label>Способ создания</label><input name="creation_method" value="Adobe Firefly"></div><div><label>Промпт</label><textarea name="prompt"></textarea></div><input type="hidden" name="status" value="Черновик"><button class="btn-primary w-full">Создать кадр</button></form>
</aside></div>
@endsection
