@extends('layouts.app')
@section('title', 'Акты, сцены и кадры')
@section('content')
@php
    $allScenes = $project->acts->flatMap->scenes;
    $shotDefaults = $allScenes->mapWithKeys(function ($scene) {
        $number = ((int) $scene->shots->max('number')) + 1;

        return [(string) $scene->id => ['number' => $number, 'code' => $scene->code.'-K'.str_pad((string) $number, 2, '0', STR_PAD_LEFT)]];
    });
    $initialSceneId = (string) old('scene_id', $allScenes->first()?->id);
    $initialShot = $shotDefaults->get($initialSceneId, ['number' => 1, 'code' => '']);
@endphp
<div class="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
    <div><p class="text-sm text-amber-500">Проект → акты → сцены → кадры</p><h1>Структура фильма</h1></div>
    @if($project->firefly_board_url)<a href="{{ $project->firefly_board_url }}" target="_blank" rel="noopener noreferrer" class="btn-secondary">Открыть доску фильма в Firefly ↗</a>@endif
</div>
<div x-data="{ form: '', sceneId: @js($initialSceneId), shotCode: @js(old('code', $initialShot['code'])), shotNumber: @js((int) old('number', $initialShot['number'])), shotDefaults: @js($shotDefaults), applyScene(id) { this.sceneId=String(id); const next=this.shotDefaults[this.sceneId]; if(next){this.shotCode=next.code;this.shotNumber=next.number;} } }" class="mt-7 grid gap-6 xl:grid-cols-[1.35fr_.65fr]">
    <section class="space-y-5">
        @foreach($project->acts as $act)
            <article class="card" x-data="{open:true,edit:false}">
                <div class="flex items-start justify-between gap-3">
                    <button type="button" @click="open=!open" class="min-w-0 flex-1 text-left"><p class="text-xs text-amber-600">Акт {{ $act->number }} · {{ $act->status }}</p><h2 class="mt-1">{{ $act->title }}</h2><p class="mt-2 text-sm text-slate-600">{{ $act->description }}</p></button>
                    <div class="flex items-center gap-2">@if($act->status !== 'Финал')<button type="button" @click="edit=!edit;open=true" class="text-sm text-amber-700">Изменить</button>@endif<button type="button" @click="open=!open" class="px-2 text-xl text-slate-400" x-text="open?'−':'+'"></button></div>
                </div>
                <form x-show="edit" x-cloak method="POST" action="{{ route('structure.update',['act',$act]) }}" class="mt-4 space-y-4 rounded-xl border border-mist-200 bg-mist-50 p-4">@csrf @method('PUT')<div class="field-grid"><div><label>Номер акта</label><input type="number" min="1" name="number" value="{{ $act->number }}" required></div><div><label>Порядок</label><input type="number" min="0" name="sort_order" value="{{ $act->sort_order }}"></div></div><div><label>Название</label><input name="title" value="{{ $act->title }}" required></div><div><label>Описание</label><textarea name="description">{{ $act->description }}</textarea></div><div class="field-grid"><div><label>План, секунд</label><input type="number" min="0" name="planned_duration_seconds" value="{{ $act->planned_duration_seconds }}"></div><div><label>Статус</label><input name="status" value="{{ $act->status }}" required></div></div><div class="flex gap-2"><button class="btn-primary">Сохранить акт</button><button type="button" @click="edit=false" class="btn-secondary">Отмена</button></div></form>
                <div x-show="open" class="mt-5 space-y-4">
                    @forelse($act->scenes as $scene)
                        <div class="rounded-2xl border border-mist-100 bg-mist-50 p-4" x-data="{editScene:false}">
                            <div class="flex flex-wrap items-start justify-between gap-3"><div class="min-w-0 flex-1"><p class="text-xs font-semibold text-amber-600">{{ $scene->code }} · {{ $scene->status }}</p><h3 class="mt-1">{{ $scene->title }}</h3><p class="mt-2 text-sm text-slate-600">{{ $scene->action_description }}</p><p class="mt-2 text-xs text-slate-500">{{ $scene->location?->name }} · {{ $scene->time_of_day }} · {{ $scene->weather }}</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('ai.index',['scene'=>$scene->id]) }}" class="btn-secondary">Проанализировать с ИИ</a>@if($scene->status==='Финал')<form method="POST" action="{{ route('structure.unlock',['scene',$scene]) }}">@csrf<button class="btn-secondary">Снять защиту</button></form>@else<button type="button" @click="editScene=!editScene" class="btn-secondary">Изменить сцену</button>@endif</div></div>
                            <form x-show="editScene" x-cloak method="POST" action="{{ route('structure.update',['scene',$scene]) }}" class="mt-4 space-y-4 rounded-xl border border-mist-200 bg-white p-4">@csrf @method('PUT')
                                <div class="grid gap-4 sm:grid-cols-3"><div><label>Акт</label><select name="act_id">@foreach($project->acts as $optionAct)<option value="{{ $optionAct->id }}" @selected($scene->act_id===$optionAct->id)>Акт {{ $optionAct->number }}</option>@endforeach</select></div><div><label>Код</label><input name="code" value="{{ $scene->code }}" required></div><div><label>Номер</label><input type="number" min="1" name="number" value="{{ $scene->number }}" required></div></div>
                                <div><label>Название</label><input name="title" value="{{ $scene->title }}" required></div><div><label>Описание действия</label><textarea name="action_description">{{ $scene->action_description }}</textarea></div>
                                <div class="field-grid"><div><label>Место</label><select name="location_id"><option value="">—</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected($scene->location_id===$location->id)>{{ $location->name }}</option>@endforeach</select></div><div><label>Ответственный</label><select name="assignee_id"><option value="">—</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected($scene->assignee_id===$user->id)>{{ $user->name }}</option>@endforeach</select></div><div><label>Время суток</label><input name="time_of_day" value="{{ $scene->time_of_day }}"></div><div><label>Погода</label><input name="weather" value="{{ $scene->weather }}"></div></div>
                                <div class="field-grid"><div><label>Персонажи</label><select name="character_ids[]" multiple class="min-h-28">@foreach($characters as $character)<option value="{{ $character->id }}" @selected($scene->characters->contains($character))>{{ $character->name }}</option>@endforeach</select></div><div><label>Реквизит</label><select name="prop_ids[]" multiple class="min-h-28">@foreach($props as $prop)<option value="{{ $prop->id }}" @selected($scene->props->contains($prop))>{{ $prop->name }}</option>@endforeach</select></div></div>
                                <div class="field-grid"><div><label>Диалог</label><textarea name="dialogue">{{ $scene->dialogue }}</textarea></div><div><label>Звуки</label><textarea name="sounds">{{ $scene->sounds }}</textarea></div></div><div class="field-grid"><div><label>План, секунд</label><input type="number" min="0" name="planned_duration_seconds" value="{{ $scene->planned_duration_seconds }}"></div><div><label>Статус</label><input name="status" value="{{ $scene->status }}" required></div></div><div class="flex gap-2"><button class="btn-primary">Сохранить сцену</button><button type="button" @click="editScene=false" class="btn-secondary">Отмена</button></div>
                            </form>
                            <div class="mt-4 grid gap-3 md:grid-cols-2">
                                @forelse($scene->shots as $shot)
                                    <div class="rounded-xl bg-white p-3" x-data="{editShot:false}"><p class="text-xs font-semibold text-amber-600">{{ $shot->code }} · {{ $shot->status }}</p><p class="mt-1 text-sm">{{ $shot->description }}</p><div class="mt-2 flex flex-wrap items-center justify-between gap-2"><p class="text-xs text-slate-500">{{ $shot->shot_size }} · {{ $shot->planned_duration_seconds }} сек.</p><div class="flex gap-3"><a href="{{ route('ai.index',['shot'=>$shot->id]) }}" class="text-xs text-amber-700">Помощь ИИ</a>@if($shot->status!=='Финал')<button type="button" @click="editShot=!editShot" class="text-xs text-amber-700">Изменить</button>@endif</div></div>
                                        <form x-show="editShot" x-cloak method="POST" action="{{ route('structure.update',['shot',$shot]) }}" class="mt-3 space-y-3 border-t border-mist-200 pt-3">@csrf @method('PUT')<input type="hidden" name="scene_id" value="{{ $scene->id }}"><div class="grid gap-3 sm:grid-cols-2"><div><label>Код</label><input name="code" value="{{ $shot->code }}" required></div><div><label>Номер</label><input type="number" min="1" name="number" value="{{ $shot->number }}" required></div></div><div><label>Описание</label><textarea name="description" required>{{ $shot->description }}</textarea></div><div class="grid gap-3 sm:grid-cols-2"><div><label>Действие героя</label><input name="hero_action" value="{{ $shot->hero_action }}"></div><div><label>Действие собаки</label><input name="dog_action" value="{{ $shot->dog_action }}"></div><div><label>Крупность</label><input name="shot_size" value="{{ $shot->shot_size }}"></div><div><label>План, секунд</label><input type="number" min="0" name="planned_duration_seconds" value="{{ $shot->planned_duration_seconds }}"></div></div><div><label>Положение камеры</label><textarea name="camera_position">{{ $shot->camera_position }}</textarea></div><div><label>Движение камеры</label><textarea name="camera_movement">{{ $shot->camera_movement }}</textarea></div><div><label>Объектив / указание</label><input name="lens" value="{{ $shot->lens }}"></div><div><label>Звук</label><textarea name="sound">{{ $shot->sound }}</textarea></div><div><label>Диалог</label><textarea name="dialogue">{{ $shot->dialogue }}</textarea></div><div><label>Способ создания</label><input name="creation_method" value="{{ $shot->creation_method }}"></div><div><label>Промпт</label><textarea name="prompt">{{ $shot->prompt }}</textarea></div><div><label>Статус</label><input name="status" value="{{ $shot->status }}" required></div><div class="flex gap-2"><button class="btn-primary">Сохранить кадр</button><button type="button" @click="editShot=false" class="btn-secondary">Отмена</button></div></form>
                                    </div>
                                @empty<p class="muted">Кадры ещё не добавлены.</p>@endforelse
                            </div>
                        </div>
                    @empty<p class="muted">Сцен пока нет.</p>@endforelse
                </div>
            </article>
        @endforeach
    </section>
    <aside class="card self-start xl:sticky xl:top-7">
        <h2>Добавить в структуру</h2><p class="mt-1 text-sm text-slate-500">Выберите, что хотите создать. Существующие элементы редактируются слева.</p>
        <div class="mt-4 grid grid-cols-3 gap-2 rounded-xl bg-mist-100 p-1 text-sm"><button type="button" @click="form=form==='act'?'':'act'" :class="form==='act'&&'bg-white shadow-sm'" class="rounded-lg px-2 py-2">+ Акт</button><button type="button" @click="form=form==='scene'?'':'scene'" :class="form==='scene'&&'bg-white shadow-sm'" class="rounded-lg px-2 py-2">+ Сцена</button><button type="button" @click="form=form==='shot'?'':'shot';if(form==='shot')applyScene(sceneId)" :class="form==='shot'&&'bg-white shadow-sm'" class="rounded-lg px-2 py-2">+ Кадр</button></div>
        <div x-show="!form" class="mt-5 rounded-xl bg-mist-50 p-4 text-sm leading-6 text-slate-600">Форма откроется после выбора. Код нового кадра и его следующий номер рассчитываются по выбранной сцене автоматически.</div>
        <form x-show="form==='act'" x-cloak method="POST" action="{{ route('acts.store') }}" class="mt-5 space-y-4">@csrf<h2>Новый акт</h2><div class="field-grid"><div><label>Номер</label><input type="number" name="number" min="1" required></div><div><label>Порядок</label><input type="number" name="sort_order" min="0" value="{{ $project->acts->count()+1 }}"></div></div><div><label>Название</label><input name="title" required></div><div><label>Описание</label><textarea name="description"></textarea></div><div><label>План, секунд</label><input type="number" name="planned_duration_seconds" min="0"></div><input type="hidden" name="status" value="Черновик"><button class="btn-primary w-full">Создать акт</button></form>
        <form x-show="form==='scene'" x-cloak method="POST" action="{{ route('scenes.store') }}" class="mt-5 space-y-4">@csrf<h2>Новая сцена</h2><div><label>Акт</label><select name="act_id" required>@foreach($project->acts as $act)<option value="{{ $act->id }}">Акт {{ $act->number }} — {{ $act->title }}</option>@endforeach</select></div><div class="field-grid"><div><label>Код</label><input name="code" placeholder="A1-S03" required></div><div><label>Номер</label><input name="number" type="number" min="1" required></div></div><div><label>Название</label><input name="title" required></div><div><label>Действие</label><textarea name="action_description"></textarea></div><div class="field-grid"><div><label>Место</label><select name="location_id"><option value="">—</option>@foreach($locations as $location)<option value="{{ $location->id }}">{{ $location->name }}</option>@endforeach</select></div><div><label>Ответственный</label><select name="assignee_id"><option value="">—</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></div><div><label>Время суток</label><input name="time_of_day"></div><div><label>Погода</label><input name="weather"></div></div><div><label>Персонажи</label><select name="character_ids[]" multiple class="min-h-28">@foreach($characters as $character)<option value="{{ $character->id }}">{{ $character->name }}</option>@endforeach</select></div><div><label>Реквизит</label><select name="prop_ids[]" multiple class="min-h-28">@foreach($props as $prop)<option value="{{ $prop->id }}">{{ $prop->name }}</option>@endforeach</select></div><div><label>Звуки</label><textarea name="sounds"></textarea></div><div><label>План, секунд</label><input type="number" name="planned_duration_seconds" min="0"></div><input type="hidden" name="status" value="Черновик"><button class="btn-primary w-full">Создать сцену</button></form>
        <form x-show="form==='shot'" x-cloak method="POST" action="{{ route('shots.store') }}" class="mt-5 space-y-4">@csrf<h2>Новый кадр</h2><div><label>Сцена, в которую добавляется кадр</label><select name="scene_id" x-model="sceneId" @change="applyScene($event.target.value)" required>@foreach($allScenes as $scene)<option value="{{ $scene->id }}">{{ $scene->code }} — {{ $scene->title }}</option>@endforeach</select></div><div class="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">Код и номер рассчитаны автоматически. При необходимости их можно исправить вручную.</div><div class="field-grid"><div><label>Код</label><input name="code" x-model="shotCode" required></div><div><label>Номер</label><input name="number" type="number" min="1" x-model.number="shotNumber" required></div></div><div><label>Описание кадра</label><textarea name="description" required></textarea></div><div class="field-grid"><div><label>Действие героя</label><input name="hero_action"></div><div><label>Действие собаки</label><input name="dog_action"></div><div><label>Крупность</label><input name="shot_size"></div><div><label>План, секунд</label><input type="number" name="planned_duration_seconds" min="0"></div></div><div><label>Положение камеры</label><textarea name="camera_position"></textarea></div><div><label>Движение камеры</label><textarea name="camera_movement"></textarea></div><div><label>Объектив / указание</label><input name="lens"></div><div><label>Звук</label><textarea name="sound"></textarea></div><div><label>Способ создания</label><input name="creation_method" value="Adobe Firefly"></div><div><label>Промпт</label><textarea name="prompt"></textarea></div><input type="hidden" name="status" value="Черновик"><button class="btn-primary w-full">Создать кадр</button></form>
    </aside>
</div>
@endsection
