@extends('layouts.app')
@section('title','Помощь')
@section('content')
@php($catalog = config('workspace_help'))
@php($articleCount = collect($catalog)->sum(fn ($category) => count($category['articles'])))
<div x-data="{ search:'', category:'all' }" x-init="$nextTick(() => { if (location.hash) { const article = document.querySelector(location.hash); if (article) { article.open = true; article.scrollIntoView({block:'center'}); } } })"><div><p class="text-sm text-amber-500">Инструкция для команды</p><h1>Помощь по рабочей зоне</h1><p class="mt-2 max-w-3xl text-slate-600">{{ $articleCount }} коротких инструкций вместо нескольких длинных статей. Найдите действие или выберите раздел.</p></div>
<div class="card mt-7"><label for="help-search">Что вы хотите сделать?</label><input id="help-search" x-model.debounce.200ms="search" type="search" placeholder="Например: загрузить MOV, создать кадр, отклонить материал…" class="mt-2"><div class="mt-4 flex flex-wrap gap-2"><button type="button" @click="category='all'" :class="category==='all' ? 'btn-primary' : 'btn-secondary'">Все темы</button>@foreach($catalog as $key => $section)<button type="button" @click="category=@js($key)" :class="category===@js($key) ? 'btn-primary' : 'btn-secondary'">{{ $section['label'] }}</button>@endforeach</div></div>
<div class="mt-7 space-y-7">@foreach($catalog as $key => $section)<section x-show="category==='all' || category===@js($key)"><div class="mb-3 flex items-end justify-between"><h2>{{ $section['label'] }}</h2><span class="text-sm text-slate-400">{{ count($section['articles']) }} тем</span></div><div class="grid gap-3 lg:grid-cols-2">@foreach($section['articles'] as $article) @php($searchText = mb_strtolower($article['title'].' '.$article['summary'].' '.implode(' ', $article['steps'])))<details id="{{ $article['id'] }}" class="card group py-4" x-show="!search || @js($searchText).includes(search.toLowerCase())"><summary class="flex cursor-pointer list-none items-center justify-between gap-4 font-semibold"><span>{{ $article['title'] }}</span><span class="text-xl text-amber-600 transition group-open:rotate-45">+</span></summary><div class="mt-4 border-t border-mist-100 pt-4 text-sm leading-6 text-slate-700"><p>{{ $article['summary'] }}</p>@if($article['steps'])<ol class="mt-3 list-decimal space-y-1 pl-5">@foreach($article['steps'] as $step)<li>{{ $step }}</li>@endforeach</ol>@endif</div></details>@endforeach</div></section>@endforeach</div>
<div class="card mt-7 bg-ink-950 text-white"><h2>Не нашли ответ?</h2><p class="mt-2 text-sm text-slate-300">Откройте нужную страницу и нажмите круглую кнопку <b>i</b> справа внизу. Там показываются инструкции именно для текущего раздела.</p></div></div>
@endsection
