<?php

$en = require __DIR__.'/../en/interface.php';

return array_replace($en, [
    'Обзор' => 'Übersicht', 'О проекте' => 'Über das Projekt', 'Акты, сцены и кадры' => 'Akte, Szenen und Einstellungen', 'Чек-лист' => 'Checkliste', 'Материалы' => 'Materialien', 'Персонажи' => 'Figuren', 'Места' => 'Drehorte', 'Реквизит и одежда' => 'Requisiten und Kostüme', 'Документы' => 'Dokumente', 'ИИ-помощник' => 'KI-Assistent', 'Публикации' => 'Veröffentlichungen', 'Команда' => 'Team', 'История изменений' => 'Änderungsverlauf',
    'Добавить материал' => 'Material hinzufügen', 'Загрузить материал' => 'Material hochladen', 'Сохранить материал' => 'Material speichern', 'Новый материал' => 'Neues Material', 'Название' => 'Titel', 'Описание' => 'Beschreibung', 'Статус' => 'Status', 'Тип' => 'Typ', 'Порядок' => 'Reihenfolge', 'Сохранить' => 'Speichern', 'Отмена' => 'Abbrechen', 'Изменить' => 'Bearbeiten', 'Создать' => 'Erstellen', 'Автор' => 'Autor', 'Источник' => 'Quelle', 'Комментарий' => 'Kommentar', 'Ответственный' => 'Verantwortlich', 'Срок' => 'Frist', 'Поиск по названию' => 'Nach Titel suchen', 'Все типы' => 'Alle Typen', 'Все статусы' => 'Alle Status', 'Применить фильтры' => 'Filter anwenden', 'Скачать оригинал' => 'Original herunterladen', 'Открыть внешний файл' => 'Externe Datei öffnen', 'Предпросмотр недоступен' => 'Keine Vorschau verfügbar', 'Обновить статус' => 'Status aktualisieren', 'Метаданные' => 'Metadaten', 'Связано' => 'Verknüpft mit', 'Файл' => 'Datei', 'Внешняя ссылка' => 'Externer Link', 'Категория' => 'Kategorie', 'Без категории' => 'Ohne Kategorie', 'Дата съёмки' => 'Aufnahmedatum',
    'Общая готовность' => 'Gesamtfortschritt', 'Выполнено' => 'Erledigt', 'Предупреждения' => 'Warnungen', 'Ожидают проверки' => 'Warten auf Prüfung', 'Готовность разделов' => 'Fortschritt der Bereiche', 'Открыть чек-лист' => 'Checkliste öffnen', 'Нужны материалы' => 'Benötigte Materialien', 'Последние материалы' => 'Neueste Materialien', 'Все материалы' => 'Alle Materialien', 'Последние изменения' => 'Letzte Änderungen', 'Сегодня' => 'Heute', 'Месяц' => 'Monat', 'Лимит' => 'Limit', 'Не задан' => 'Nicht festgelegt', 'Текст' => 'Text', 'Изображения' => 'Bilder', 'Ошибки' => 'Fehler', 'Данных пока нет.' => 'Noch keine Daten.', 'Материалов пока нет.' => 'Noch keine Materialien.',
    'Производственный чек-лист' => 'Produktionscheckliste', 'Пересчитать всё' => 'Alles neu berechnen', 'Требования' => 'Anforderungen', 'Не завершено' => 'Nicht abgeschlossen', 'Добавить требование' => 'Anforderung hinzufügen', 'Отметить вручную' => 'Manuell markieren', 'Сохранить решение' => 'Entscheidung speichern', 'Новый пункт' => 'Neuer Punkt', 'Раздел / группа' => 'Bereich / Gruppe', 'Обязательный пункт' => 'Pflichtpunkt', 'Создать пункт' => 'Punkt erstellen', 'Новый раздел' => 'Neuer Bereich', 'Родительский раздел' => 'Übergeordneter Bereich', 'Верхний уровень' => 'Oberste Ebene', 'Создать раздел' => 'Bereich erstellen',
    'Производственная библиотека' => 'Produktionsbibliothek', 'Новая запись' => 'Neuer Eintrag', 'Роль' => 'Rolle', 'Возраст' => 'Alter', 'Внешность' => 'Aussehen', 'Телосложение' => 'Körperbau', 'Одежда' => 'Kostüm', 'Голос' => 'Stimme', 'Движения' => 'Bewegung', 'Время суток' => 'Tageszeit', 'Погода' => 'Wetter', 'Свет' => 'Licht', 'Палитра' => 'Palette', 'Звуки' => 'Geräusche', 'Цвет' => 'Farbe', 'Размеры' => 'Abmessungen', 'Состояние' => 'Zustand',
    'Документы проекта' => 'Projektdokumente', 'Редактировать сценарий' => 'Drehbuch bearbeiten', 'Отменить редактирование' => 'Bearbeitung abbrechen', 'Работа с текстом через ИИ' => 'Textarbeit mit KI', 'Тип документа' => 'Dokumenttyp', 'Текст сценария' => 'Drehbuchtext', 'Комментарий к версии' => 'Versionskommentar', 'Сохранить новую версию' => 'Neue Version speichern', 'История версий' => 'Versionsverlauf', 'Восстановить эту версию' => 'Diese Version wiederherstellen',
    'Структура фильма' => 'Filmstruktur', 'Новый акт' => 'Neuer Akt', 'Новая сцена' => 'Neue Szene', 'Новый кадр' => 'Neue Einstellung', 'Номер' => 'Nummer', 'Код' => 'Code', 'Действие' => 'Handlung', 'Действие героя' => 'Handlung der Hauptfigur', 'Действие собаки' => 'Handlung des Hundes', 'Крупность' => 'Einstellungsgröße', 'Положение камеры' => 'Kameraposition', 'Движение камеры' => 'Kamerabewegung', 'Звук' => 'Ton', 'Способ создания' => 'Erstellungsmethode', 'Промпт' => 'Prompt', 'Создать акт' => 'Akt erstellen', 'Создать сцену' => 'Szene erstellen', 'Создать кадр' => 'Einstellung erstellen', 'Кадры ещё не добавлены.' => 'Noch keine Einstellungen.', 'Сцен пока нет.' => 'Noch keine Szenen.', 'Проанализировать сцену с ИИ' => 'Szene mit KI analysieren',
    'Карточка проекта' => 'Projektkarte', 'Редактировать карточку' => 'Projektkarte bearbeiten', 'Слоган' => 'Slogan', 'Логлайн' => 'Logline', 'Синопсис' => 'Synopsis', 'Визуальный принцип' => 'Visuelles Prinzip', 'Звуковой принцип' => 'Tonkonzept', 'Камера и цвет' => 'Kamera und Farbe', 'Параметры' => 'Spezifikationen', 'Жанр' => 'Genre', 'Продолжительность' => 'Dauer', 'Формат' => 'Format', 'Частота' => 'Bildrate', 'Язык' => 'Sprache', 'Стадия' => 'Phase', 'Редактирование проекта' => 'Projekt bearbeiten', 'Новая версия карточки' => 'Neue Kartenversion', 'Краткий синопсис' => 'Kurze Synopsis', 'Сохранить новую версию' => 'Neue Version speichern',
    'Все участники имеют одинаковые права' => 'Alle Mitglieder haben die gleichen Rechte', 'Активен' => 'Aktiv', 'Отключён' => 'Deaktiviert', 'Новый пароль (необязательно)' => 'Neues Passwort (optional)', 'Повторите пароль' => 'Passwort wiederholen', 'Добавить участника' => 'Teammitglied hinzufügen', 'Имя' => 'Name', 'Электронная почта' => 'E-Mail-Adresse', 'Пароль' => 'Passwort', 'Добавить' => 'Hinzufügen',
    'Ничего не публикуется автоматически' => 'Nichts wird automatisch veröffentlicht', 'Публичная страница' => 'Öffentliche Website', 'Открыть сайт' => 'Website öffnen', 'Главная страница' => 'Startseite', 'Пожертвования' => 'Spenden', 'На сайте' => 'Auf der Website', 'Не показывается' => 'Ausgeblendet', 'Скрыть с сайта' => 'Von Website entfernen', 'Показать на сайте' => 'Auf Website zeigen', 'Новая публикация' => 'Neue Veröffentlichung', 'Создать и опубликовать' => 'Erstellen und veröffentlichen', 'Сохранить как черновик' => 'Als Entwurf speichern', 'Добавить новый материал' => 'Neues Medium hinzufügen', 'Загрузить фото или видео' => 'Foto oder Video hochladen', 'Выбрать из медиатеки' => 'Aus Mediathek wählen', 'Сохранить изменения' => 'Änderungen speichern', 'Публикаций пока нет.' => 'Noch keine Veröffentlichungen.', 'Оформление главной' => 'Gestaltung der Startseite', 'Опубликованный контакт' => 'Öffentlicher Kontakt', 'Сохранить остальные настройки' => 'Weitere Einstellungen speichern', 'Посмотреть публичный сайт' => 'Öffentliche Website ansehen', 'Поддержать создание фильма' => 'Filmproduktion unterstützen', 'Банковские реквизиты' => 'Bankverbindung', 'Показывать блок на публичной странице' => 'Block auf öffentlicher Website anzeigen', 'Сохранить настройки' => 'Einstellungen speichern',
    'Работа с текстом' => 'Textarbeit', 'Собственное задание' => 'Eigene Aufgabe', 'Дополнительные требования' => 'Zusätzliche Anforderungen', 'Исходный текст' => 'Ausgangstext', 'Получить предложение' => 'Vorschlag erstellen', 'Название результата' => 'Titel des Ergebnisses', 'Тип изображения' => 'Bildtyp', 'Качество' => 'Qualität', 'Низкое' => 'Niedrig', 'Среднее' => 'Mittel', 'Высокое' => 'Hoch', 'Количество вариантов' => 'Anzahl der Varianten', 'Создать новое' => 'Neu erstellen', 'Поставить в очередь' => 'In Warteschlange stellen', 'История моих запросов' => 'Meine Anfragen', 'Запросов ещё нет.' => 'Noch keine Anfragen.', 'Применить' => 'Übernehmen', 'Отклонить' => 'Ablehnen', 'Скопировать' => 'Kopieren', 'Доработать' => 'Überarbeiten',
    'Защита от случайной перезаписи' => 'Schutz vor versehentlichem Überschreiben', 'Показать изменённые поля' => 'Geänderte Felder anzeigen', 'Было' => 'Vorher', 'Стало' => 'Nachher', 'Изменений пока нет.' => 'Noch keine Änderungen.', 'Восстановить состояние до правки' => 'Stand vor dieser Änderung wiederherstellen',
]);
