@extends('layouts.app')
@section('title','ИИ-помощник')
@section('content')
<div><p class="text-sm text-amber-500">OpenAI Responses API · предложения требуют подтверждения</p><h1>ИИ-помощник</h1><p class="mt-2 max-w-3xl text-slate-600">Сначала выберите основной объект. Его текст подставится автоматически и не изменится, пока вы явно не примете результат.</p></div>
<section class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><div class="card"><p class="muted">Сегодня</p><p class="mt-2 text-2xl font-semibold">${{ number_format($usage['today'],4) }}</p></div><div class="card"><p class="muted">Текущий месяц</p><p class="mt-2 text-2xl font-semibold">${{ number_format($usage['month'],4) }}</p></div><div class="card"><p class="muted">Текстовые запросы</p><p class="mt-2 text-2xl font-semibold">{{ $usage['text'] }}</p></div><div class="card"><p class="muted">Изображения</p><p class="mt-2 text-2xl font-semibold">{{ $usage['images'] }}</p></div><div class="card"><p class="muted">Ошибки API</p><p class="mt-2 text-2xl font-semibold">{{ $usage['errors'] }}</p></div></section>
<div x-data="{
    tab: 'text',
    targets: @js($targets),
    subjectType: @js(old('subject_type', $initial['type'])),
    subjectId: @js((string) old('subject_id', $initial['id'])),
    targetField: @js(old('target_field', $initial['field'])),
    sourceText: @js(old('source_text', $initial['source'])),
    sceneIds: @js(array_map('intval', old('scene_ids', $initial['scene_ids']))),
    shotIds: @js(array_map('intval', old('shot_ids', $initial['shot_ids']))),
    assetIds: @js(array_map('intval', old('asset_ids', $initial['asset_ids']))),
    defaultField(type) { return {document:'content',project:'logline',scene:'action_description',shot:'description'}[type] || ''; },
    changeType() { const ids=Object.keys(this.targets[this.subjectType] || {}); this.subjectId=ids[0] || ''; this.targetField=this.defaultField(this.subjectType); this.loadTarget(); },
    loadTarget() { const item=(this.targets[this.subjectType] || {})[String(this.subjectId)]; if(!item){this.sourceText='';return;} this.sourceText=item.fields[this.targetField] || ''; this.sceneIds=item.scene_id?[Number(item.scene_id)]:[]; this.shotIds=item.shot_id?[Number(item.shot_id)]:[]; this.assetIds=(item.asset_ids || []).map(Number); },
    loadField() { const item=(this.targets[this.subjectType] || {})[String(this.subjectId)]; if(item)this.sourceText=item.fields[this.targetField] || ''; }
}" class="mt-7">
    <div class="flex gap-2"><button type="button" @click="tab='text'" :class="tab==='text'?'bg-ink-900 text-white':'bg-white'" class="rounded-xl px-4 py-2">Работа с текстом</button><button type="button" @click="tab='image'" :class="tab==='image'?'bg-ink-900 text-white':'bg-white'" class="rounded-xl px-4 py-2">Изображения</button></div>
    <form x-show="tab==='text'" method="POST" action="{{ route('ai.text') }}" class="card mt-5 space-y-5">
        @csrf
        <section class="rounded-2xl border border-amber-300 bg-amber-50 p-4">
            <h2>1. Что анализируем</h2><p class="mt-1 text-sm text-slate-600">Выбор здесь заменяет исходный текст и определяет, куда можно применить принятое предложение.</p>
            <div class="mt-4 grid gap-4 md:grid-cols-3">
                <div><label>Тип объекта</label><select x-model="subjectType" @change="changeType()"><option value="">Текст без привязки</option><option value="document">Документ</option><option value="project">Карточка проекта</option><option value="scene">Сцена</option><option value="shot">Кадр</option></select></div>
                <div x-show="subjectType==='document'"><label>Документ</label><select x-model="subjectId" @change="loadTarget()"><option value="">—</option>@foreach($documents as $item)<option value="{{ $item->id }}">{{ $item->title }}</option>@endforeach</select></div>
                <div x-show="subjectType==='scene'"><label>Сцена</label><select x-model="subjectId" @change="loadTarget()"><option value="">—</option>@foreach($scenes as $item)<option value="{{ $item->id }}">{{ $item->code }} — {{ $item->title }}</option>@endforeach</select></div>
                <div x-show="subjectType==='shot'"><label>Кадр</label><select x-model="subjectId" @change="loadTarget()"><option value="">—</option>@foreach($shots as $item)<option value="{{ $item->id }}">{{ $item->code }} — {{ \Illuminate\Support\Str::limit($item->description, 55) }}</option>@endforeach</select></div>
                <div x-show="subjectType==='document'"><label>Поле</label><select x-model="targetField" @change="loadField()"><option value="content">Текст документа</option></select></div>
                <div x-show="subjectType==='project'"><label>Поле проекта</label><select x-model="targetField" @change="loadField()"><option value="logline">Логлайн</option><option value="synopsis">Синопсис</option><option value="visual_principle">Визуальный принцип</option><option value="sound_principle">Звуковой принцип</option></select></div>
                <div x-show="subjectType==='scene'"><label>Поле сцены</label><select x-model="targetField" @change="loadField()"><option value="action_description">Описание действия</option><option value="dialogue">Диалог</option><option value="sounds">Звуки</option><option value="notes">Комментарии</option></select></div>
                <div x-show="subjectType==='shot'"><label>Поле кадра</label><select x-model="targetField" @change="loadField()"><option value="description">Описание</option><option value="prompt">Промпт</option><option value="negative_prompt">Отрицательный промпт</option><option value="camera_movement">Движение камеры</option><option value="sound">Звук</option><option value="dialogue">Диалог</option></select></div>
            </div>
            <input type="hidden" name="subject_type" :value="subjectType"><input type="hidden" name="subject_id" :value="subjectId"><input type="hidden" name="target_field" :value="targetField">
        </section>
        <div class="field-grid"><div><label>2. Действие</label><select name="action">@foreach($actions as $key=>$label)<option value="{{ $key }}" @selected(old('action')===$key)>{{ $label }}</option>@endforeach</select></div><div><label>Собственное задание</label><input name="custom_instruction" value="{{ old('custom_instruction') }}" placeholder="Дополнительные требования"></div></div>
        <div class="grid gap-4 xl:grid-cols-2"><div><label>Исходный текст</label><textarea class="min-h-64" name="source_text" x-model="sourceText" required></textarea><p class="mt-1 text-xs text-slate-500">Текст подставляется из выбранного объекта, но перед запросом его можно исправить вручную.</p></div><div><label>Вторая версия для сравнения (необязательно)</label><textarea class="min-h-64" name="secondary_text">{{ old('secondary_text') }}</textarea></div></div>
        <section><h2>3. Дополнительный контекст</h2><p class="mt-1 text-sm text-slate-500">Эти списки не заменяют исходный текст. Они только дают ИИ справочную информацию. Для выбора нескольких пунктов используйте Ctrl или Cmd.</p><div class="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-5"><label class="flex gap-2"><input type="checkbox" name="include_project" value="1" class="h-4 w-4" @checked(old('include_project'))><span>Карточка проекта</span></label><div><label>Документы</label><select multiple name="document_ids[]" class="min-h-36">@foreach($documents as $item)<option value="{{ $item->id }}" @selected(in_array($item->id,old('document_ids',[])))>{{ $item->title }}</option>@endforeach</select></div><div><label>Сцены</label><select multiple name="scene_ids[]" x-model.number="sceneIds" class="min-h-36">@foreach($scenes as $item)<option value="{{ $item->id }}">{{ $item->code }} — {{ $item->title }}</option>@endforeach</select></div><div><label>Кадры</label><select multiple name="shot_ids[]" x-model.number="shotIds" class="min-h-36">@foreach($shots as $item)<option value="{{ $item->id }}">{{ $item->code }}</option>@endforeach</select></div><div><label>Материалы из медиатеки</label><select multiple name="asset_ids[]" x-model.number="assetIds" class="min-h-36">@foreach($assets as $item)<option value="{{ $item->id }}">{{ $item->title }}</option>@endforeach</select><p class="mt-1 text-xs text-slate-500" x-text="assetIds.length ? `Связано/выбрано: ${assetIds.length}` : 'У объекта нет прикреплённых материалов'"></p></div></div></section>
        <button class="btn-primary">Получить предложение</button>
    </form>
    <form x-show="tab==='image'" x-cloak method="POST" action="{{ route('ai.images') }}" enctype="multipart/form-data" class="card mt-5 space-y-5">
        @csrf
        <div class="field-grid"><div><label>Название результата</label><input name="title" required></div><div><label>Тип изображения</label><select name="image_type"><option>Концепт-арт</option><option>Персонаж</option><option>Одежда</option><option>Место</option><option>Реквизит</option><option>Раскадровка</option><option>Начальный кадр</option><option>Конечный кадр</option><option>Афиша</option></select></div></div><div><label>Описание</label><textarea class="min-h-40" name="description" required></textarea></div>
        <div class="field-grid"><div><label>Стиль</label><input name="style" value="Мягкая винтажная акварельная эстетика, приглушённая осенне-холодная палитра"></div><div><label>Дополнительные указания</label><input name="additional_instructions"></div><div><label>Формат</label><select name="size"><option>1536x1024</option><option>1024x1024</option><option>1024x1536</option><option>2048x2048</option><option>2048x1152</option><option>3840x2160</option><option>2160x3840</option></select></div><div><label>Качество</label><select name="quality"><option value="low">Низкое</option><option value="medium" selected>Среднее</option><option value="high">Высокое</option></select></div><div><label>Количество вариантов</label><input type="number" name="count" min="1" max="4" value="1"></div><div><label>Редактировать исходное изображение</label><select name="source_asset_id"><option value="">Создать новое</option>@foreach($assets->filter(fn($item)=>str_starts_with((string)$item->mime_type,'image/')) as $item)<option value="{{ $item->id }}">{{ $item->title }}</option>@endforeach</select></div><div><label>Референсы из медиатеки</label><select multiple name="reference_asset_ids[]" class="min-h-28">@foreach($assets->filter(fn($item)=>str_starts_with((string)$item->mime_type,'image/')) as $item)<option value="{{ $item->id }}">{{ $item->title }}</option>@endforeach</select></div><div><label>Загрузить референсы</label><input type="file" name="reference_files[]" accept="image/jpeg,image/png,image/webp" multiple><p class="mt-1 text-xs text-slate-400">До четырёх изображений. Они сохранятся приватно.</p></div></div>
        <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-5">@foreach([['character_ids','Персонажи',$characters],['location_ids','Места',$locations],['scene_ids','Сцены',$scenes],['shot_ids','Кадры',$shots],['checklist_item_ids','Чек-лист',$checklistItems]] as [$field,$label,$items])<div><label>{{ $label }}</label><select multiple name="{{ $field }}[]" class="min-h-36">@foreach($items as $item)<option value="{{ $item->id }}" @selected(($field==='scene_ids' && in_array($item->id,$initial['scene_ids'])) || ($field==='shot_ids' && in_array($item->id,$initial['shot_ids'])))>{{ $item->code ?? $item->name ?? $item->title }}</option>@endforeach</select></div>@endforeach</div><button class="btn-primary">Поставить в очередь</button>
    </form>
</div>
<section class="mt-7 card"><h2>История моих запросов</h2><div class="mt-4 divide-y divide-mist-100">@forelse($requests as $request)<a href="{{ route('ai.show',$request) }}" class="flex flex-wrap items-center justify-between gap-3 py-3 first:pt-0"><div><p class="font-medium">{{ $request->request_type }} · {{ $request->action }}</p><p class="mt-1 text-xs text-slate-500">{{ $request->model }} · {{ $request->created_at->format('d.m.Y H:i') }}</p></div><div class="text-right"><span class="badge {{ $request->status==='Ошибка'?'bg-red-100 text-red-700':'bg-mist-100' }}">{{ $request->status }}</span><p class="mt-1 text-xs text-slate-400">${{ number_format($request->cost,4) }}</p></div></a>@empty<p class="muted">Запросов ещё нет.</p>@endforelse</div></section>
@endsection
