@extends('layouts.app')
@section('title','Запрос ИИ')
@section('content')
<div class="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><p class="text-sm text-amber-500">{{ $request->request_type }} · {{ $request->model }}</p><h1>Запрос #{{ $request->id }}</h1></div><span class="badge {{ $request->status==='Ошибка'?'bg-red-100 text-red-700':'bg-mist-100' }}">{{ $request->status }}</span></div>
@if($request->error_message)<div class="mt-6 rounded-2xl border border-red-200 bg-red-50 p-5 text-red-800"><h2>API не выполнил запрос</h2><p class="mt-2">{{ $request->error_message }}</p><p class="mt-2 text-sm">Исходный текст сохранён ниже и не изменён.</p></div>@endif
@if($request->request_type==='Текст')<div class="mt-7 grid gap-6 xl:grid-cols-2"><article class="card"><p class="text-xs uppercase tracking-wider text-slate-400">Исходный текст</p><div class="prose-film mt-4">{{ $request->source_text }}</div></article><article class="card"><p class="text-xs uppercase tracking-wider text-amber-600">Предложение ИИ</p><div id="ai-result" class="prose-film mt-4">{{ $request->result_text ?: 'Результат не получен.' }}</div></article></div>@if($request->result_text)<form method="POST" action="{{ route('ai.decision',$request) }}" class="card mt-6 flex flex-wrap gap-3">@csrf<button name="decision" value="apply" class="btn-primary">Применить</button><button name="decision" value="save_version" class="btn-secondary">Сохранить как новую версию</button><button name="decision" value="copy" @click="navigator.clipboard.writeText(document.getElementById('ai-result').innerText)" class="btn-secondary">Скопировать</button><button name="decision" value="revise" class="btn-secondary">Доработать</button><button name="decision" value="reject" class="btn-danger">Отклонить</button></form>@endif
@else<div class="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3">@forelse($request->generatedAssets as $generated)<a href="{{ route('assets.show',$generated->asset) }}" class="card overflow-hidden p-0"><img src="{{ route('assets.preview',$generated->asset) }}" alt="{{ $generated->asset->title }}" class="h-72 w-full object-cover"><div class="p-4"><h2>{{ $generated->asset->title }}</h2><p class="mt-2 text-sm text-slate-500">Статус: {{ $generated->asset->status }}. Требуется ручная проверка.</p></div></a>@empty<div class="card muted">Изображения ещё не готовы. Для очереди должен работать <code>php artisan queue:work</code>.</div>@endforelse</div>@endif
<div class="mt-6 text-xs text-slate-400">Вход: {{ $request->input_tokens }} токенов · выход: {{ $request->output_tokens }} · изображений: {{ $request->image_count }} · расход: ${{ number_format($request->cost,6) }}</div>
@endsection
