@extends('layouts.app')
@section('title', 'Новый материал')
@section('content')
<div><p class="text-sm text-amber-500">Оригинал хранится в закрытом хранилище</p><h1>Добавить материал</h1></div>
<form x-data="{ uploading:false, progress:0, error:'', send(e){ this.uploading=true; this.error=''; const x=new XMLHttpRequest(); x.open('POST',e.target.action); x.setRequestHeader('Accept','application/json'); x.upload.onprogress=(v)=>{if(v.lengthComputable)this.progress=Math.round(v.loaded/v.total*100)}; x.onload=()=>{if(x.status>=200&&x.status<400){location.href=x.responseURL}else{this.uploading=false; try{const r=JSON.parse(x.responseText);this.error=Object.values(r.errors||{}).flat().join(' ')}catch(_){this.error='Не удалось загрузить материал.'}}}; x.onerror=()=>{this.uploading=false;this.error='Ошибка сети.'}; x.send(new FormData(e.target)); } }" @submit.prevent="send($event)" method="POST" action="{{ route('assets.store') }}" enctype="multipart/form-data" class="card mt-7 space-y-6">@csrf
<div x-show="error" x-text="error" class="rounded-xl bg-red-50 p-3 text-sm text-red-700"></div><div class="field-grid"><div><label>Название</label><input name="title" required></div><div><label>Тип материала</label><select name="type" required>@foreach(\App\Models\Asset::TYPES as $type)<option>{{ $type }}</option>@endforeach</select></div></div><div><label>Описание</label><textarea name="description"></textarea></div>
<div class="grid gap-5 rounded-2xl bg-mist-50 p-4 md:grid-cols-3"><div><label>Файл</label><input type="file" name="file"><p class="mt-1 text-xs text-slate-400">До {{ number_format(config('production.max_upload_kb')/1024) }} МБ</p></div><div><label>Внешняя ссылка</label><input type="url" name="external_url" placeholder="https://…"></div><div><label>Текстовая заметка</label><textarea name="text_content" class="min-h-24"></textarea></div><p class="text-xs text-slate-500 md:col-span-3">Укажите файл, ссылку или текст. Для больших видео допустима внешняя ссылка.</p></div>
<div class="field-grid"><div><label>Категория</label><select name="category_id"><option value="">Без категории</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->scope }} · {{ $category->name }}</option>@endforeach</select></div><div><label>Вид / ракурс</label><input name="view_angle"></div><div><label>Статус</label><select name="status">@foreach(\App\Models\Asset::STATUSES as $status)<option @selected($status==='На проверке')>{{ $status }}</option>@endforeach</select></div><div><label>Дата съёмки</label><input type="date" name="captured_at"></div><div><label>Автор</label><input name="author"></div><div><label>Источник</label><input name="source"></div></div>
<section><h2>Связи материала</h2><p class="mt-1 muted">Один материал можно одновременно привязать к нескольким объектам. Сцены и кадры необязательны. Связь с пунктом чек-листа позволяет материалу автоматически выполнить требование этого пункта.</p><div class="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">@foreach([['character_ids','Персонажи',$characters],['location_ids','Места',$locations],['prop_ids','Реквизит',$props],['act_ids','Акты',$acts],['scene_ids','Сцены',$scenes],['shot_ids','Кадры',$shots],['checklist_item_ids','Пункты чек-листа',$checklistItems]] as [$field,$label,$items])<div><label>{{ $label }}</label><select name="{{ $field }}[]" multiple class="min-h-32">@foreach($items as $item)<option value="{{ $item->id }}">{{ $item->code ?? $item->name ?? $item->title }}</option>@endforeach</select></div>@endforeach</div></section>
<div><label>Комментарий</label><textarea name="comment"></textarea></div><label class="flex items-center gap-2"><input type="checkbox" name="has_usage_permission" value="1" class="h-4 w-4"><span>Есть разрешение на использование</span></label><div x-show="uploading" class="rounded-xl bg-mist-50 p-3"><div class="flex justify-between text-sm"><span>Загрузка…</span><span x-text="progress+'%'"></span></div><div class="mt-2 h-2 overflow-hidden rounded-full bg-white"><div class="h-full bg-amber-500 transition-all" :style="`width:${progress}%`"></div></div></div><div class="flex gap-3"><button :disabled="uploading" class="btn-primary">Сохранить материал</button><a href="{{ route('assets.index') }}" class="btn-secondary">Отмена</a></div></form>
@endsection
