@extends('layouts.app')
@section('title', 'Редактирование материала')
@section('content')
<div><p class="text-sm text-amber-500">Оригинальный файл при редактировании не изменяется</p><h1>Редактировать материал</h1></div>
<form method="POST" action="{{ route('assets.update', $asset) }}" class="card mt-7 space-y-6">@csrf @method('PUT')
<div class="field-grid"><div><label>Название</label><input name="title" value="{{ old('title', $asset->title) }}" required></div><div><label>Тип материала</label><select name="type" required>@foreach(\App\Models\Asset::TYPES as $type)<option @selected(old('type', $asset->type)===$type)>{{ $type }}</option>@endforeach</select></div></div>
<div><label>Описание</label><textarea name="description">{{ old('description', $asset->description) }}</textarea></div>
<div class="grid gap-5 rounded-2xl bg-mist-50 p-4 md:grid-cols-2"><div><label>Внешняя ссылка</label><input type="url" name="external_url" value="{{ old('external_url', $asset->external_url) }}" placeholder="https://…"></div><div><label>Текстовая заметка</label><textarea name="text_content" class="min-h-24">{{ old('text_content', $asset->text_content) }}</textarea></div>@if($asset->file_path)<p class="text-xs text-slate-500 md:col-span-2">Загруженный оригинал сохранён. Для замены файла создайте новый материал, чтобы не потерять исходник.</p>@endif</div>
<div class="field-grid"><div><label>Категория</label><select name="category_id"><option value="">Без категории</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)old('category_id', $asset->category_id)===(string)$category->id)>{{ $category->scope }} · {{ $category->name }}</option>@endforeach</select></div><div><label>Вид / ракурс</label><input name="view_angle" value="{{ old('view_angle', $asset->view_angle) }}"></div><div><label>Статус</label><select name="status">@foreach(\App\Models\Asset::STATUSES as $status)<option @selected(old('status', $asset->status)===$status)>{{ $status }}</option>@endforeach</select></div><div><label>Дата съёмки</label><input type="date" name="captured_at" value="{{ old('captured_at', $asset->captured_at?->format('Y-m-d')) }}"></div><div><label>Автор</label><input name="author" value="{{ old('author', $asset->author) }}"></div><div><label>Источник</label><input name="source" value="{{ old('source', $asset->source) }}"></div></div>
@php($links = ['character_ids'=>$asset->characters->modelKeys(),'location_ids'=>$asset->locations->modelKeys(),'prop_ids'=>$asset->props->modelKeys(),'act_ids'=>$asset->acts->modelKeys(),'scene_ids'=>$asset->scenes->modelKeys(),'shot_ids'=>$asset->shots->modelKeys(),'checklist_item_ids'=>$asset->checklistItems->modelKeys()])
<section><h2>Связи материала</h2><p class="mt-1 muted">Сцены и кадры указывать необязательно. Связь с пунктом чек-листа позволяет материалу автоматически выполнить требование этого пункта.</p><div class="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">@foreach([['character_ids','Персонажи',$characters],['location_ids','Места',$locations],['prop_ids','Реквизит',$props],['act_ids','Акты',$acts],['scene_ids','Сцены',$scenes],['shot_ids','Кадры',$shots],['checklist_item_ids','Пункты чек-листа',$checklistItems]] as [$field,$label,$items])<div><label>{{ $label }}</label><select name="{{ $field }}[]" multiple class="min-h-32">@foreach($items as $item)<option value="{{ $item->id }}" @selected(in_array($item->id, old($field, $links[$field]), true))>{{ $item->code ?? $item->name ?? $item->title }}</option>@endforeach</select></div>@endforeach</div></section>
<div><label>Комментарий</label><textarea name="comment">{{ old('comment', $asset->comment) }}</textarea></div><label class="flex items-center gap-2"><input type="checkbox" name="has_usage_permission" value="1" class="h-4 w-4" @checked(old('has_usage_permission', $asset->has_usage_permission))><span>Есть разрешение на использование</span></label>
<div class="flex gap-3"><button class="btn-primary">Сохранить изменения</button><a href="{{ route('assets.show', $asset) }}" class="btn-secondary">Отмена</a></div></form>
@endsection
