@extends('layouts.app')
@section('title', $asset->title)
@section('content')
<div class="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><p class="text-sm text-amber-500">{{ $asset->type }} · {{ $asset->category?->name }}</p><h1>{{ $asset->title }}</h1><p class="mt-2 text-slate-600">{{ $asset->description }}</p></div><div class="flex flex-wrap gap-3"><a class="btn-primary" href="{{ route('assets.edit',$asset) }}">Редактировать</a>@if($asset->file_path)<a class="btn-secondary" href="{{ route('assets.download',$asset) }}">Скачать оригинал</a>@endif<form method="POST" action="{{ route('assets.destroy', $asset) }}" onsubmit="return confirm('Удалить материал «{{ addslashes($asset->title) }}» из рабочей зоны? Исходный файл останется в защищённом хранилище.')">@csrf @method('DELETE')<button class="btn-secondary text-red-700">Удалить</button></form></div></div>
@php($isVideo = $asset->file_path && ($asset->type === 'Видео' || str_starts_with((string) $asset->mime_type, 'video/')))
@php($isAudio = $asset->file_path && ($asset->type === 'Аудио' || str_starts_with((string) $asset->mime_type, 'audio/')))
<div class="mt-7 grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><section class="card">@if($isVideo)<video controls playsinline preload="metadata" class="mx-auto max-h-[520px] w-full rounded-xl bg-black"><source src="{{ route('assets.preview',$asset) }}" type="{{ $asset->mime_type ?: 'video/quicktime' }}">Ваш браузер не умеет воспроизводить этот видеофайл.</video><div class="mt-4 rounded-xl bg-mist-50 p-3 text-sm text-slate-600"><p><b>Видео загружено.</b> Используйте кнопку воспроизведения. Если MOV с iPhone не открывается, браузер не поддерживает кодек этого файла — скачайте оригинал или откройте страницу в Safari.</p><a class="mt-2 inline-block font-semibold text-amber-700 underline" href="{{ route('assets.download',$asset) }}">Скачать оригинал</a></div>@elseif($isAudio)<audio controls preload="metadata" class="w-full"><source src="{{ route('assets.preview',$asset) }}" type="{{ $asset->mime_type }}"></audio>@elseif($asset->thumbnail_path)<img src="{{ route('assets.thumbnail',$asset) }}" alt="{{ $asset->title }}" class="mx-auto max-h-[420px] max-w-full rounded-xl object-contain">@elseif($asset->text_content)<div class="prose-film">{{ $asset->text_content }}</div>@elseif($asset->external_url)<a class="text-amber-700 underline" href="{{ $asset->external_url }}" target="_blank" rel="noopener">Открыть внешний файл</a>@else<div class="grid min-h-60 place-items-center rounded-xl bg-ink-900 text-mist-200">Предпросмотр недоступен</div>@endif</section>
<aside class="space-y-5"><div class="card"><h2>Проверка</h2><form x-data="{ status: @js(old('status', $asset->status)), reviewComment: @js(old('review_comment', $asset->review_comment) ?? '') }" method="POST" action="{{ route('assets.status',$asset) }}" class="mt-4 space-y-3">@csrf @method('PUT')<div><label>Статус</label><select name="status" x-model="status">@foreach(\App\Models\Asset::STATUSES as $status)<option @selected(old('status', $asset->status)===$status)>{{ $status }}</option>@endforeach</select></div><div><label>Комментарий проверки</label><textarea name="review_comment" x-model="reviewComment" :required="status === 'Отклонено' || status === 'Требуется переснять'"></textarea><p class="mt-1 text-xs" :class="(status === 'Отклонено' || status === 'Требуется переснять') ? (reviewComment.trim() ? 'text-emerald-700' : 'text-red-700') : 'text-slate-400'" x-text="(status === 'Отклонено' || status === 'Требуется переснять') ? (reviewComment.trim() ? 'Комментарий сохранён и будет показан загрузившему материал человеку.' : 'Обязательно напишите, что исправить. Этот комментарий увидит загрузивший материал человек.') : 'Можно оставить пояснение для команды.'"></p></div><button class="btn-primary w-full">Обновить статус</button></form></div><div class="card"><h2>Связано</h2><div class="mt-3 space-y-3 text-sm">@foreach(['Персонажи'=>$asset->characters,'Места'=>$asset->locations,'Реквизит'=>$asset->props,'Сцены'=>$asset->scenes,'Кадры'=>$asset->shots,'Чек-лист'=>$asset->checklistItems] as $label=>$items)@if($items->isNotEmpty())<div><p class="text-xs uppercase tracking-wide text-slate-400">{{ $label }}</p><p class="mt-1">{{ $items->map(fn($x)=>$x->code ?? $x->name ?? $x->title)->join(', ') }}</p></div>@endif @endforeach</div></div><div class="card text-sm"><h2>Метаданные</h2><dl class="mt-3 space-y-2"><div class="flex justify-between"><dt class="text-slate-500">Автор</dt><dd>{{ $asset->author ?: '—' }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">Источник</dt><dd>{{ $asset->source ?: '—' }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">Разрешение</dt><dd>{{ $asset->has_usage_permission?'Есть':'Не указано' }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">Загрузил</dt><dd>{{ $asset->uploader?->name }}</dd></div></dl></div></aside></div>
@endsection
